version: '3.8'

services:
  frontend:
    build:
      context: ./web/webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./web/webapp:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./services/search_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/search_service:/app
      - /app/__pycache__
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pensionos
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pensionos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 